CREATE TABLE providers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE games (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    provider_id INTEGER NOT NULL,
    CONSTRAINT fk_games_provider
        FOREIGN KEY (provider_id)
        REFERENCES providers(id)
);

CREATE TABLE game_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id INTEGER NOT NULL,
    game_id INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL,
    CONSTRAINT fk_sessions_game
        FOREIGN KEY (game_id)
        REFERENCES games(id)
);